spring:
  application:
    name: Rent-A-Thing
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:/db/changelog/changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  upload:
    dir: ./uploads